apiVersion: apps/v1
kind: Deployment
metadata:
  name: tb3_teleop
spec:
  selector:
    matchLabels:
      app: tb3_teleop
  template:
    metadata:
      labels:
        app: tb3_teleop
    spec:
      containers:
      - name: tb3_teleop
        image: robinlab/cmr_tb3_bringup
        env:
        - name: ROS_MASTER_URI
          value: http://192.168.0.112:11311
        - name: ROS_IP
          value: 192.168.0.207
      hostNetwork: true
